framework:
    secret:          something_secure
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    validation:      { enabled: true }
    csrf_protection: false
    session:         ~
    default_locale:  en
    translator:      { fallback: en }
    profiler:        { only_exceptions: false }
    templating:
        engines: ['twig']